import {
	App,
	Editor,
	MarkdownView,
	Modal,
	Notice,
	Plugin,
	PluginSettingTab,
	Setting,
	TFile,
	TFolder,
	debounce,
} from "obsidian";
import * as fs from "fs";
import * as path from "path";

interface SyncTarget {
	id: string;
	name: string;
	enabled: boolean;
	outputPath: string;
	template: string;
	description: string;
}

interface AIContextSyncSettings {
	sourceNotePath: string;
	autoSyncOnSave: boolean;
	showStatusBar: boolean;
	syncTargets: SyncTarget[];
	customHeader: string;
	includeTimestamp: boolean;
	projectPaths: string[];
}

const DEFAULT_TARGETS: SyncTarget[] = [
	{
		id: "claude",
		name: "Claude Code",
		enabled: true,
		outputPath: "CLAUDE.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Claude Code's context file (CLAUDE.md)",
	},
	{
		id: "agents",
		name: "AGENTS.md (Universal)",
		enabled: true,
		outputPath: "AGENTS.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Universal standard - works with Codex, DeepSeek, and others",
	},
	{
		id: "cursor-rules",
		name: "Cursor Rules",
		enabled: true,
		outputPath: ".cursor/rules/ai-context.md",
		template:
			"---\ndescription: Project context and conventions synced from Obsidian\nglobs: *\nalwaysApply: true\n---\n\n{{CONTENT}}",
		description: "Cursor's rules system - works with all Cursor models (GPT, Claude, Gemini, etc.)",
	},
	{
		id: "copilot",
		name: "GitHub Copilot",
		enabled: false,
		outputPath: ".github/copilot-instructions.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "GitHub Copilot custom instructions",
	},
	{
		id: "windsurf",
		name: "Windsurf (Codeium)",
		enabled: false,
		outputPath: ".windsurfrules",
		template: "{{CONTENT}}",
		description: "Windsurf/Codeium rules file",
	},
	{
		id: "continue",
		name: "Continue.dev",
		enabled: false,
		outputPath: ".continuerules",
		template: "{{CONTENT}}",
		description: "Continue.dev rules for VS Code/JetBrains",
	},
	{
		id: "cody",
		name: "Sourcegraph Cody",
		enabled: false,
		outputPath: ".cody/instructions.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Sourcegraph Cody context instructions",
	},
	{
		id: "aider",
		name: "Aider",
		enabled: false,
		outputPath: ".aider.conf.yml",
		template: "# Aider configuration\n# Context from Obsidian\n\nread:\n  - AGENTS.md",
		description: "Aider config (references AGENTS.md)",
	},
	{
		id: "codex",
		name: "OpenAI Codex CLI",
		enabled: false,
		outputPath: "AGENTS.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "OpenAI Codex CLI reads AGENTS.md",
	},
	{
		id: "chatgpt-memory",
		name: "ChatGPT (Memory Export)",
		enabled: false,
		outputPath: ".chatgpt/project-context.md",
		template: "# Project Context for ChatGPT\n\nCopy this into ChatGPT's memory or paste at conversation start.\n\n---\n\n{{CONTENT}}",
		description: "Export for manual ChatGPT memory/context",
	},
	{
		id: "deepseek",
		name: "DeepSeek Coder",
		enabled: false,
		outputPath: "DEEPSEEK.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "DeepSeek Coder context file",
	},
	{
		id: "gemini",
		name: "Google Gemini",
		enabled: false,
		outputPath: ".gemini/context.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Google Gemini/AI Studio context",
	},
	{
		id: "amazon-q",
		name: "Amazon Q Developer",
		enabled: false,
		outputPath: ".amazonq/rules.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Amazon Q Developer rules",
	},
	{
		id: "zed",
		name: "Zed AI",
		enabled: false,
		outputPath: ".zed/assistant/context.md",
		template: "{{HEADER}}\n\n{{CONTENT}}",
		description: "Zed editor AI assistant context",
	},
];

const DEFAULT_SETTINGS: AIContextSyncSettings = {
	sourceNotePath: "",
	autoSyncOnSave: true,
	showStatusBar: true,
	syncTargets: DEFAULT_TARGETS,
	customHeader:
		"<!-- AI Context - Auto-generated by obsidian-ai-context-sync -->\n<!-- Source: Obsidian vault - Do not edit directly -->",
	includeTimestamp: true,
	projectPaths: [],
};

export default class AIContextSyncPlugin extends Plugin {
	settings: AIContextSyncSettings = DEFAULT_SETTINGS;
	statusBarItem: HTMLElement | null = null;
	private debouncedSync: ReturnType<typeof debounce>;

	async onload() {
		await this.loadSettings();

		this.debouncedSync = debounce(
			() => this.syncToAllTargets(),
			1000,
			true
		);

		if (this.settings.showStatusBar) {
			this.statusBarItem = this.addStatusBarItem();
			this.updateStatusBar("idle");
		}

		this.addCommand({
			id: "sync-ai-context",
			name: "Sync AI context to all targets",
			callback: () => this.syncToAllTargets(),
		});

		this.addCommand({
			id: "sync-ai-context-select",
			name: "Sync AI context to specific target",
			callback: () => this.showTargetSelector(),
		});

		this.addCommand({
			id: "set-source-note",
			name: "Set current note as AI context source",
			editorCallback: (editor: Editor, view: MarkdownView) => {
				if (view.file) {
					this.settings.sourceNotePath = view.file.path;
					this.saveSettings();
					new Notice(
						`Set "${view.file.basename}" as AI context source`
					);
				}
			},
		});

		this.addCommand({
			id: "add-project-path",
			name: "Add project path for sync targets",
			callback: () => this.showAddProjectPathModal(),
		});

		this.addCommand({
			id: "create-ai-context-template",
			name: "Create AI context template note",
			callback: () => this.createTemplateNote(),
		});

		if (this.settings.autoSyncOnSave) {
			this.registerEvent(
				this.app.vault.on("modify", (file) => {
					if (
						file instanceof TFile &&
						file.path === this.settings.sourceNotePath
					) {
						this.debouncedSync();
					}
				})
			);
		}

		this.addSettingTab(new AIContextSyncSettingTab(this.app, this));

		this.addRibbonIcon("refresh-cw", "Sync AI Context", () => {
			this.syncToAllTargets();
		});
	}

	onunload() {}

	async loadSettings() {
		this.settings = Object.assign(
			{},
			DEFAULT_SETTINGS,
			await this.loadData()
		);
		if (!this.settings.syncTargets || this.settings.syncTargets.length === 0) {
			this.settings.syncTargets = DEFAULT_TARGETS;
		}
	}

	async saveSettings() {
		await this.saveData(this.settings);
	}

	updateStatusBar(status: "idle" | "syncing" | "success" | "error") {
		if (!this.statusBarItem) return;

		const icons: Record<string, string> = {
			idle: "🔄",
			syncing: "⏳",
			success: "✅",
			error: "❌",
		};

		this.statusBarItem.setText(`AI Sync: ${icons[status]}`);
	}

	async syncToAllTargets() {
		if (!this.settings.sourceNotePath) {
			new Notice(
				"No source note configured. Use 'Set current note as AI context source' command."
			);
			return;
		}

		const sourceFile = this.app.vault.getAbstractFileByPath(
			this.settings.sourceNotePath
		);
		if (!(sourceFile instanceof TFile)) {
			new Notice(`Source note not found: ${this.settings.sourceNotePath}`);
			return;
		}

		this.updateStatusBar("syncing");

		try {
			const content = await this.app.vault.read(sourceFile);
			const enabledTargets = this.settings.syncTargets.filter(
				(t) => t.enabled
			);

			if (enabledTargets.length === 0) {
				new Notice("No sync targets enabled. Check plugin settings.");
				this.updateStatusBar("idle");
				return;
			}

			const projectPaths =
				this.settings.projectPaths.length > 0
					? this.settings.projectPaths
					: [this.getVaultBasePath()];

			let successCount = 0;
			let errorCount = 0;

			for (const projectPath of projectPaths) {
				for (const target of enabledTargets) {
					try {
						await this.syncToTarget(target, content, projectPath);
						successCount++;
					} catch (e) {
						console.error(
							`Failed to sync to ${target.name} at ${projectPath}:`,
							e
						);
						errorCount++;
					}
				}
			}

			if (errorCount === 0) {
				new Notice(
					`Synced to ${successCount} target(s) across ${projectPaths.length} project(s)`
				);
				this.updateStatusBar("success");
			} else {
				new Notice(
					`Synced with errors: ${successCount} succeeded, ${errorCount} failed`
				);
				this.updateStatusBar("error");
			}

			setTimeout(() => this.updateStatusBar("idle"), 3000);
		} catch (e) {
			console.error("Sync failed:", e);
			new Notice(`Sync failed: ${e}`);
			this.updateStatusBar("error");
		}
	}

	async syncToTarget(target: SyncTarget, content: string, projectPath: string) {
		const header = this.settings.includeTimestamp
			? `${this.settings.customHeader}\n<!-- Last synced: ${new Date().toISOString()} -->`
			: this.settings.customHeader;

		const processedContent = target.template
			.replace("{{HEADER}}", header)
			.replace("{{CONTENT}}", content)
			.replace("{{TIMESTAMP}}", new Date().toISOString())
			.replace("{{SOURCE}}", this.settings.sourceNotePath);

		const fullPath = path.join(projectPath, target.outputPath);
		const dir = path.dirname(fullPath);

		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}

		fs.writeFileSync(fullPath, processedContent, "utf-8");
	}

	async syncToSpecificTarget(targetId: string) {
		const target = this.settings.syncTargets.find((t) => t.id === targetId);
		if (!target) {
			new Notice(`Target not found: ${targetId}`);
			return;
		}

		if (!this.settings.sourceNotePath) {
			new Notice("No source note configured.");
			return;
		}

		const sourceFile = this.app.vault.getAbstractFileByPath(
			this.settings.sourceNotePath
		);
		if (!(sourceFile instanceof TFile)) {
			new Notice(`Source note not found: ${this.settings.sourceNotePath}`);
			return;
		}

		try {
			const content = await this.app.vault.read(sourceFile);
			const projectPaths =
				this.settings.projectPaths.length > 0
					? this.settings.projectPaths
					: [this.getVaultBasePath()];

			for (const projectPath of projectPaths) {
				await this.syncToTarget(target, content, projectPath);
			}

			new Notice(`Synced to ${target.name}`);
		} catch (e) {
			new Notice(`Failed to sync to ${target.name}: ${e}`);
		}
	}

	showTargetSelector() {
		new TargetSelectorModal(this.app, this).open();
	}

	showAddProjectPathModal() {
		new AddProjectPathModal(this.app, this).open();
	}

	async createTemplateNote() {
		const templateContent = `# AI Context

> This note is your single source of truth for AI coding assistant context.
> It will be synced to CLAUDE.md, .cursor/rules/, AGENTS.md, and more.

## Project Overview

<!-- Describe your project here -->

## Tech Stack

- Language: 
- Framework: 
- Database: 

## Coding Conventions

### Style Guide

- 

### File Organization

- 

## Important Patterns

### Architecture

- 

### Common Patterns

- 

## Things to Avoid

- 

## Additional Context

<!-- Any other context that helps AI assistants understand your codebase -->
`;

		const fileName = "AI Context.md";
		const existingFile = this.app.vault.getAbstractFileByPath(fileName);

		if (existingFile) {
			new Notice(
				`"${fileName}" already exists. Opening it instead.`
			);
			if (existingFile instanceof TFile) {
				this.app.workspace.getLeaf().openFile(existingFile);
			}
			return;
		}

		const newFile = await this.app.vault.create(fileName, templateContent);
		this.settings.sourceNotePath = newFile.path;
		await this.saveSettings();

		this.app.workspace.getLeaf().openFile(newFile);
		new Notice(
			`Created "${fileName}" and set it as the source note`
		);
	}

	getVaultBasePath(): string {
		const adapter = this.app.vault.adapter;
		if ("basePath" in adapter) {
			return (adapter as any).basePath;
		}
		return "";
	}
}

class TargetSelectorModal extends Modal {
	plugin: AIContextSyncPlugin;

	constructor(app: App, plugin: AIContextSyncPlugin) {
		super(app);
		this.plugin = plugin;
	}

	onOpen() {
		const { contentEl } = this;
		contentEl.createEl("h2", { text: "Select sync target" });

		const enabledTargets = this.plugin.settings.syncTargets.filter(
			(t) => t.enabled
		);

		if (enabledTargets.length === 0) {
			contentEl.createEl("p", {
				text: "No targets enabled. Configure targets in settings.",
			});
			return;
		}

		for (const target of enabledTargets) {
			new Setting(contentEl)
				.setName(target.name)
				.setDesc(target.description)
				.addButton((btn) =>
					btn.setButtonText("Sync").onClick(() => {
						this.plugin.syncToSpecificTarget(target.id);
						this.close();
					})
				);
		}
	}

	onClose() {
		const { contentEl } = this;
		contentEl.empty();
	}
}

class AddProjectPathModal extends Modal {
	plugin: AIContextSyncPlugin;

	constructor(app: App, plugin: AIContextSyncPlugin) {
		super(app);
		this.plugin = plugin;
	}

	onOpen() {
		const { contentEl } = this;
		contentEl.createEl("h2", { text: "Add project path" });
		contentEl.createEl("p", {
			text: "Enter the absolute path to your project directory where AI context files should be synced.",
		});

		let inputValue = "";

		new Setting(contentEl).setName("Project path").addText((text) =>
			text
				.setPlaceholder("/path/to/your/project")
				.onChange((value) => {
					inputValue = value;
				})
		);

		new Setting(contentEl).addButton((btn) =>
			btn
				.setButtonText("Add")
				.setCta()
				.onClick(async () => {
					if (inputValue && !this.plugin.settings.projectPaths.includes(inputValue)) {
						this.plugin.settings.projectPaths.push(inputValue);
						await this.plugin.saveSettings();
						new Notice(`Added project path: ${inputValue}`);
					}
					this.close();
				})
		);
	}

	onClose() {
		const { contentEl } = this;
		contentEl.empty();
	}
}

class AIContextSyncSettingTab extends PluginSettingTab {
	plugin: AIContextSyncPlugin;

	constructor(app: App, plugin: AIContextSyncPlugin) {
		super(app, plugin);
		this.plugin = plugin;
	}

	display(): void {
		const { containerEl } = this;
		containerEl.empty();

		containerEl.createEl("h1", { text: "AI Context Sync" });
		containerEl.createEl("p", {
			text: "Sync your AI context notes to multiple AI coding assistants from a single source of truth.",
			cls: "setting-item-description",
		});

		containerEl.createEl("h2", { text: "Source Configuration" });

		new Setting(containerEl)
			.setName("Source note")
			.setDesc(
				"The Obsidian note that contains your AI context. Use the command 'Set current note as AI context source' to set this."
			)
			.addText((text) =>
				text
					.setPlaceholder("path/to/your/note.md")
					.setValue(this.plugin.settings.sourceNotePath)
					.onChange(async (value) => {
						this.plugin.settings.sourceNotePath = value;
						await this.plugin.saveSettings();
					})
			);

		new Setting(containerEl)
			.setName("Auto-sync on save")
			.setDesc(
				"Automatically sync when the source note is modified"
			)
			.addToggle((toggle) =>
				toggle
					.setValue(this.plugin.settings.autoSyncOnSave)
					.onChange(async (value) => {
						this.plugin.settings.autoSyncOnSave = value;
						await this.plugin.saveSettings();
					})
			);

		new Setting(containerEl)
			.setName("Show status bar")
			.setDesc("Show sync status in the status bar")
			.addToggle((toggle) =>
				toggle
					.setValue(this.plugin.settings.showStatusBar)
					.onChange(async (value) => {
						this.plugin.settings.showStatusBar = value;
						await this.plugin.saveSettings();
					})
			);

		new Setting(containerEl)
			.setName("Include timestamp")
			.setDesc("Add a timestamp comment to synced files")
			.addToggle((toggle) =>
				toggle
					.setValue(this.plugin.settings.includeTimestamp)
					.onChange(async (value) => {
						this.plugin.settings.includeTimestamp = value;
						await this.plugin.saveSettings();
					})
			);

		containerEl.createEl("h2", { text: "Sync Targets" });
		containerEl.createEl("p", {
			text: "Configure which AI tools to sync your context to.",
			cls: "setting-item-description",
		});

		for (const target of this.plugin.settings.syncTargets) {
			const targetSetting = new Setting(containerEl)
				.setName(target.name)
				.setDesc(`${target.description} → ${target.outputPath}`)
				.addToggle((toggle) =>
					toggle.setValue(target.enabled).onChange(async (value) => {
						target.enabled = value;
						await this.plugin.saveSettings();
					})
				);
		}

		containerEl.createEl("h2", { text: "Project Paths" });
		containerEl.createEl("p", {
			text: "Directories where AI context files will be synced. If empty, syncs to the Obsidian vault root.",
			cls: "setting-item-description",
		});

		for (let i = 0; i < this.plugin.settings.projectPaths.length; i++) {
			const projectPath = this.plugin.settings.projectPaths[i];
			new Setting(containerEl)
				.setName(projectPath)
				.addButton((btn) =>
					btn
						.setButtonText("Remove")
						.setWarning()
						.onClick(async () => {
							this.plugin.settings.projectPaths.splice(i, 1);
							await this.plugin.saveSettings();
							this.display();
						})
				);
		}

		new Setting(containerEl).addButton((btn) =>
			btn.setButtonText("Add project path").onClick(() => {
				this.plugin.showAddProjectPathModal();
			})
		);

		containerEl.createEl("h2", { text: "Advanced" });

		new Setting(containerEl)
			.setName("Custom header")
			.setDesc(
				"Header comment added to synced files (use {{TIMESTAMP}} for dynamic timestamp)"
			)
			.addTextArea((text) =>
				text
					.setValue(this.plugin.settings.customHeader)
					.onChange(async (value) => {
						this.plugin.settings.customHeader = value;
						await this.plugin.saveSettings();
					})
			);

		containerEl.createEl("h2", { text: "Actions" });

		new Setting(containerEl)
			.setName("Sync now")
			.setDesc("Manually trigger a sync to all enabled targets")
			.addButton((btn) =>
				btn
					.setButtonText("Sync All")
					.setCta()
					.onClick(() => {
						this.plugin.syncToAllTargets();
					})
			);

		new Setting(containerEl)
			.setName("Create template")
			.setDesc("Create a starter AI context note with common sections")
			.addButton((btn) =>
				btn.setButtonText("Create Template").onClick(() => {
					this.plugin.createTemplateNote();
				})
			);
	}
}
